name: Release Packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          yarn config set npmAuthToken ${{secrets.GITHUB_TOKEN}}
          yarn install --immutable
          yarn config unset npmAuthToken

      - name: Build packages
        # run: yarn g:build
        run: |
          yarn sdk @helix-bridge/v2-sdk build
          yarn sdk @helix-bridge/v3-sdk build

      - name: Publish to GitHub Packages
        run: |
          npm publish -w @helix-bridge/v2-sdk
          npm publish -w @helix-bridge/v3-sdk
        # npm publish -w @helix-bridge/sdk-core
        # npm publish -w @helix-bridge/universal-router-sdk
        # npm publish -w @helix-bridge/uniswapx-sdk
        # npm publish -w @helix-bridge/router-sdk
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
